### ISSUE TITLE
Expose Source (Input) as an Entity

### ISSUE THREAD

**Issue by dandashl1973** [hchris1/Eversolo#111]
### Is your feature request related to a problem? Please describe.

Changing the Input on a Streamer has always been a challenge for the non-technical members of my family.  I like to listen to music with Tidal, through the Eversolo's "Internal Player" input.  Others just want to use Sonos.  I have a Sonos port attached to the Coax SPDIF port of the DMP-A6 to satisfy them.  If I have a few too many glasses of wine and forget to change the Input on the Eversolo back to Coaxial In when I'm done, I get an earful.... apparently loading up the Eversolo app to change the input is too painful for them. :(.   

### Describe the solution you'd like

I would love it if the Eversolo's Source (Input) could be exposed as an Entity in the integration.  I could just create an automation, when the Sonos starts playing, Set the DMP-A6's Source to Coaxial In

### Describe alternatives you've considered

I found an undocumented API on the Zidoo forums where I can actually change the DMP-A6's input with an HTTP POST, which I could do but this seems very messy.  

### Additional context

I am a newbie to Home Assistant, and I might be totally off base here.  I notice that the Source is present when I click on the integration's default card - perhaps I'm missing how to access it from the automations setup?

<img width="591" alt="Screenshot 2024-12-26 at 7 13 03 PM" src="https://github.com/user-attachments/assets/14e02c96-0373-44f0-a02b-fd916b26733c" />

**Comment by hchris1** [comment]
Hi @dandashl1973,

You are right. The integration uses the **Source** feature that the Home Assistant media player entity already offers. That's why I didn't put that in a separate select dropdown.

You can access that in automations, too:
1. Create a new automation
2. Add your triggers as you want
3. Add the action. Search for "source". You should see something like: Mediaplayer: Select source
4. Select it and choose the Eversolo media player entity
5. Enter the name of the Source you want to switch to, e.g., "Coaxial In".

The name for the source can both be the translation ("Coaxial In") or the internal Eversolo name ("RCA"). This wouldn't break the automation in case the Eversolo language is changed. Here is the mapping:

| Translated Name | Internal Name |
| - | - |
|Internal player | XMOS |
| Bluetooth In | BT |
| USB-C In | USB |
| Optical In | SPDIF |
| Coaxial In | RCA |

Let me know if that worked :)

Cheers,
Christian

**Comment by dandashl1973** [comment]
Ha!  Works perfectly.

As a newbie, I guess I don’t really understand the relationship of how the entity features and properties all fit together.

Thanks so much for your help. :)

**Comment by hchris1** [comment]
Great to hear that! I will close the issue then.

In case you like the integration so far, I would really appreciate giving it a star or even [buying me a coffee](https://buymeacoffee.com/hchris1) :)

Cheers,
Christian
