### ISSUE TITLE
possible bug when selecting source

### ISSUE THREAD

**Issue by therobster121** [hchris1/Eversolo#27]
### Describe the issue

Since last update when I attempt to change source to a specific source via a template I get the following error.
"Failed to call service media_player/select_source. coroutine raised StopIteration"

when changing source via the eversolo media player control it works fine.

### Reproduction steps

1. Create a template card similar to below:

content: Mediaplayer music
entity: media_player.eversolo
icon: mdi:music
icon_color: 
tap_action:
  action: call-service
  data:
    source: Internal Player
    service: media_player.select_source
  target:
    entity_id: media_player.eversolo
type: template

2. click button
3. error  is observerd "Failed to call service media_player/select_source. coroutine raised StopIteration"

**Comment by hchris1** [comment]
That's interesting! The last update changed the select source a bit because it now loads the source options from the device instead of hardcoding them.

I'll try recreate the issue and investigate.

**Comment by hchris1** [comment]
First an explanation why the error was thrown:
In the `select_source` method, it looks for the given source in the source dictionary. In version 0.3, I changed this so it's created from the Eversolo response. This means that it's now language specific. It looks like this:
```json
{
    "XMOS": "Interner Player", 
    "BT": "Bluetooth-Eingang", 
    "USB": "USB-C-Eingang", 
    "SPDIF": "Optischer Eingang", 
    "RCA": "Koaxialer Eingang"
}
```

The `select_source` method used the `next` method to look for the given source value in the dictionary. If it doesn't find it, it will throw a `StopIteration` exception. For some reason it can't find the source that you have given. However, I didn't find any bug in the implementation.

I don't like that a service called from a template stops working with a hardcoded source if you change the language of the Eversolo device. Because of this, I introduced the following changes in Version 0.3.2:
- `select_source` both accepts the key or the value from the dictionary shown above. This means that in my example you could call it with source `XMOS` or `Interner Player`.
![image](https://github.com/hchris1/Eversolo/assets/34690225/8d0f6346-a44a-4bbe-89a9-f3a3465e5e26)
![image](https://github.com/hchris1/Eversolo/assets/34690225/7f2c0304-74c1-46f9-aca7-e07723999a24)
- `select_source` now raises a `ValueError` instead of a `StopIteration` when the source is not found.

Looking forward to your feedback!
Chris

**Comment by therobster121** [comment]
Thanks Chris

It works now  I also realise that I was using “Internal Player” which was
working before  but it should now be “Internal player” for the EN version
so therefore was case sensitive.

I think Eversolo are actually inconsistent in the naming but we can’t do
anything about that.

I think you can close the issue.
